version: '3.8'

services:
  backend:
    container_name: backend
    image: backend-image
    build:
      context: ./backend/src
    env_file:
      - ./backend/src/Quests.API/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5158
    ports:
      - "8001:5158"

  frontend:
    container_name: frontend
    image: frontend-image
    build:
      context: ./frontend
    ports:
      - "3001:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:5158
volumes:
  postgres-data: